env:
  - HUGO_VERSION=0.40.1

branches:
  only:
  - master

install:
  - wget https://github.com/gohugoio/hugo/releases/download/v${HUGO_VERSION}/hugo_${HUGO_VERSION}_Linux-64bit.deb
  - sudo dpkg -i hugo*.deb

script:
  - hugo

deploy:
  - provider: script
    script: chmod +x ./scripts/deploy.sh && ./scripts/deploy.sh
    skip_cleanup: true
    on:
      branch: master