dist: trusty

install:
  - wget https://github.com/gohugoio/hugo/releases/download/v${HUGO_VERSION}/hugo_${HUGO_VERSION}_Linux-64bit.deb
  - sudo dpkg -i hugo*.deb

script:
  - if [ "$TRAVIS_BRANCH" = "master" ]; then URL="bleidner.me"; else URL="beta.bleidner.me"; fi
  - hugo --baseURL="https://$URL"

addons:
  ssh_known_hosts: w00b42f4.kasserver.com

before_deploy:
- openssl aes-256-cbc -K $encrypted_2de3a86ad4c5_key -iv $encrypted_2de3a86ad4c5_iv
  -in deploy_rsa.enc -out /tmp/deploy_rsa -d
- eval "$(ssh-agent -s)"
- chmod 600 /tmp/deploy_rsa
- ssh-add /tmp/deploy_rsa

deploy:
  - provider: script
    script: chmod +x ./deploy.sh && ./deploy.sh $MASTER_DIR
    skip_cleanup: true
    on:
      branch: master

  - provider: script
    script: chmod +x ./deploy.sh && ./deploy.sh $BETA_DIR
    skip_cleanup: true
    on:
      branch: develop
