# safelist
branches:
  only:
  - master

install:
- wget https://github.com/gohugoio/hugo/releases/download/v0.40.1/hugo_0.40.1_Linux-64bit.deb
- sudo dpkg -i hugo*.deb

script:
- hugo

deploy:
  - provider: script
    script: chmod +x ./scripts/deploy.sh && ./scripts/deploy.sh
    skip_cleanup: true
    on:
      branch: master