## Basic Configuration

baseurl = "https://beta.bleidner.me"
builddrafts = false
canonifyurls = false
languageCode = "de-DE"

contentdir = "content"
layoutdir = "layouts"
publishdir = "public"

author = "Sascha Bleidner"
title = "Sascha Bleidner"

theme = "hugo-goa"

## Hugo Built-in Features
#disqusShortname = "https-shenoybr-github-io-hugo-goa-demo" # Comment out to disable Disqus.
#googleAnalytics = "XYZ"
enableRobotsTXT = true

## Site Settings
[params]
author = "Sascha Bleidner"
intro = "[@itemis](https://www.itemis.com/de/)"
description = "Software Craftsman | TDD Purist | DevOps Engineer"
authorimage = "avatar.png"
dateformat = "Jan 2, 2006"

## Site Meta Settings
[params.meta]
description = "Sascha Bleidner"
keywords = "tdd purist, software craftsmen, developer, devops engineer"

## Social Accounts
[params.social]
github = "tribunex"
#instagram = "<username>"
xing = "Sascha_Bleidner"
#linkedin = "<username>"
twitter = "sbleidner"
#facebook = "<username>"
#google = "<username>"
#googlescholar = "<account_id>"
#stackoverflow = "<username>"
#lastfm = "<username>"
#goodreads = "<username>"
#gitlab = "<username>"
#bitbucket = "<username>"
#fivehundredpx = "<username>"
#flickr = "<username>"
#foursquare = "<username>"
#hackernews = "<username>"
#kickstarter = "<username>"
#patreon = "<username>"
#pintrest = "<username>"
#steam = "<username>"
#reddit = "<username>"
#snapchat = "<username>"
#youtube = "<channelid>"
#keybase = "<username>"
#twitch = "<username>"
#soundcloud = "<username>"
#tumblr = "<username>"
#strava = "<username>"
#skype = "<username>"
#telegram = "<username>"
#whatsapp = "<username>"
email = "blog@sascha-bleidner.de"


## Extras
[params.extra]
copyright = "[Impressum](/impressum)."
poweredby = true
highlightjs = true
socialmarkup = true
toc = false
displayrssicon = false
rss = true


## Main Menu
[[menu.main]]
    name = "About"
    identifier = "about"
    weight = -30
    url = "/about/"
[[menu.main]]
    name = "Blog"
    weight = -20
    identifier = "blog"
    url = "/blog/"
[[menu.main]]
    name = "Werke"
    identifier = "werke"
    weight = -10
    url = "/werke/"
