baseurl             = "https://sascha-bleidner.de/"
builddrafts         = false
canonifyurls        = true
contentdir          = "content"
languageCode        = "de-DE"
layoutdir           = "layouts"
publishdir          = "public"
theme               = "cocoa"
author              = "Sascha Bleidner"
title               = "Sascha Bleidner"
pygmentsuseclasses  = true
pluralizelisttitles = false

[permalinks]
blog  = "blog/:slug/"

[[menu.main]]
name                   = "Home"
weight                 = -120
identifier             = "home"
url                    = "/"

[params]
include_rss            = true                          # include RSS <link> tag in <head> and show RSS icon
latestpostscount       = 5                             # how many posts to display on the home page
i18n_flags             = false                         # whether to display small country flags for available translations
author                 = "Sascha Bleidner"
cachebuster            = true                          # add the current unix timestamp in query string for cache busting css assets
dateform               = "Jan 2, 2006"
dateformfull           = "Mon Jan 2 2006 15:04:05 MST"
description            = "Home Autoamtion, Programming & Tech"
email                  = "blog(at)ascha-bleidner.de"
extracssfiles          = [ "/css/override.css" ]       # In your `static` directory, add/remove files as necessary.
faviconfile            = "img/leaf.ico"
github                 = "//github.com/tribuneX"
lang                   = "de"
noshowreadtime         = true                         # if true, don't show "<x> minutes read" in posts
selfintro              = ""                            # appears in the site header when set to a non-empty string
twitter                = "//twitter.com/sbleidner"

highlightjs            = true
# highlightjslanguages = ["go"]                        # additional languages not included in the "common" set
# highlightjsStyle     = "darcula"

piwik                  = true                         # If true, Piwik integration is enabled
piwik_url            = "//piwik.cbs-service.net/"    # URL to your Piwik installation. Must End with a slash
piwik_id             = 24                             # Id of your site in Piwik

avatar                 = "img/avatar.png" # path to image in static dir e.g img/avatar.png (do not use in the same time as gravatar)